name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Deploy to PythonAnywhere
        env:
          PYTHONANYWHERE_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          PYTHONANYWHERE_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        run: |
          python -c "
          import requests
          import os
          
          username = os.environ['PYTHONANYWHERE_USERNAME']
          token = os.environ['PYTHONANYWHERE_API_TOKEN']
          domain_name = 'MIkhailOktSu.pythonanywhere.com'
          host = 'www.pythonanywhere.com'
          remote_path_1 = '/home/MIkhailOktSu/bot.py'
          remote_path_2 = '/home/MIkhailOktSu/requirements.txt'
          local_path_1 = 'bot.py'
          local_path_2 = 'requirements.txt'
          
          url = f'https://www.pythonanywhere.com/api/v0/user/{username}/files/path{remote_path_1}'
          
          with open(local_path_1, 'rb') as file:
              response_1 = requests.post(
                  url,
                  headers={'Authorization': f'Token {token}'},
                  files={'content': file}
              )

          if response_1.status_code == 200:
              print('Файл bot.py успешно загружен!')
          else:
              print(f'Ошибка: {response_1.status_code}, {response_1.text}') 
              
          url = f'https://www.pythonanywhere.com/api/v0/user/{username}/files/path{remote_path_2}'

          with open(local_path_2, 'rb') as file:
              response_2 = requests.post(
                  url,
                  headers={'Authorization': f'Token {token}'},
                  files={'content': file}
              )

          if response_2.status_code == 200:
              print('Файл requirements.txt успешно загружен!')
          else:
              print(f'Ошибка: {response_2.status_code}, {response_2.text}') "

          


