name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Deploy to PythonAnywhere
        env:
          PYTHONANYWHERE_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          PYTHONANYWHERE_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        run: |

          pip install requests
          
          python -c "
          import requests
          import os
          
          username = os.environ['PYTHONANYWHERE_USERNAME']
          api_token = os.environ['PYTHONANYWHERE_API_TOKEN']
          base_url = f'https://www.pythonanywhere.com/api/v0/user/{username}/'

          response = requests.post(
             f'{base_url}webapps/MIkhailOktSu.pythonanywhere.com/reload/',
             headers={'Authorization': f'Token {api_token}'},
          )

          if response.status_code == 200:
             print('Приложение успешно перезапущено!')
          else:
             print(f'Ошибка: {response.status_code}, {response.text}')
          "
