name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to PythonAnywhere
        env:
          PYTHONANYWHERE_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          PYTHONANYWHERE_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        run: |
          
          pip install pythonanywhere

        
          pythonanywhere login --username $PYTHONANYWHERE_USERNAME --api-token $PYTHONANYWHERE_API_TOKEN

          
          pythonanywhere upload_file --username $PYTHONANYWHERE_USERNAME --remote_path /home/$PYTHONANYWHERE_USERNAME/my_app --local_path .

         
          pythonanywhere run_command --username $PYTHONANYWHERE_USERNAME "pip install -r /home/$PYTHONANYWHERE_USERNAME/my_app/requirements.txt"

          
          pythonanywhere reload_webapp --username $PYTHONANYWHERE_USERNAME
