name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Deploy to PythonAnywhere
        env:
          PYTHONANYWHERE_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          PYTHONANYWHERE_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        run: |
          python -c "
          import requests
          import os
          
          username = os.environ['PYTHONANYWHERE_USERNAME']
          token = os.environ['PYTHONANYWHERE_API_TOKEN']

          
          remote_path_prefix = '/home/MIkhailOktSu/'
          local_path_1 = 'bot.py'
          local_path_2 = 'requirements.txt'

          # Upload bot.py
          remote_path_1 = remote_path_prefix + 'bot.py'
          url_1 = f'https://www.pythonanywhere.com/api/v0/user/{username}/files/path{remote_path_1}'

          with open(local_path_1, 'rb') as file:
              response_1 = requests.post(
                  url_1,
                  headers={'Authorization': f'Token {token}'},
                  files={'content': file}
              )

          if response_1.status_code == 200:
              print('File bot.py uploaded successfully!')
          else:
              print(f'Error: {response_1.status_code}, {response_1.text}')

          # Upload  requirements.txt
          remote_path_2 = remote_path_prefix + 'requirements.txt'
          url_2 = f'https://www.pythonanywhere.com/api/v0/user/{username}/files/path{remote_path_2}'

          with open(local_path_2, 'rb') as file:
              response_2 = requests.post(
                  url_2,
                  headers={'Authorization': f'Token {token}'},
                  files={'content': file}
              )

          if response_2.status_code == 200:
              print('File requirements.txt uploaded successfully!')
          else:
              print(f'Error: {response_2.status_code}, {response_2.text}') "


              # Install dependencies
          python -c "
          import requests
          import os
          
          username = os.environ['PYTHONANYWHERE_USERNAME']
          token = os.environ['PYTHONANYWHERE_API_TOKEN']



          base_url = f'https://www.pythonanywhere.com/api/v0/user/{username}/'

          response = requests.post(
              f'{base_url}bash/',
              headers={'Authorization': f'Token {token}'},
              json={
                  'command': 'pip install -r /home/{username}/requirements.txt'
              }
          )
          if response.status_code == 200:
              print('Dependencies installed successfully!')
          else:
              print(f'Error: {response.status_code}, {response.text}')
          "



          


